name: 'Action generate changelog'
description: 'This action generate a changelog'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  path:
    description: 'package.json path'
    required: false
outputs:
  success:
    description: 'the result will be printed here'
runs:
  using: 'composite'
  steps:
    - name: Add changelog in package.json
      shell: bash
      run: ls
      run: echo "rodando changelogs..."
      run: bash changelog.sh
    - uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: 'run action'
      shell: bash
      run: 'dist/index.js'